-- AUTO-GENERATED -- DO NOT HAND-EDIT.
-- Regenerated by scripts/mismo_db_refresh.py on 2026-08-19. See docs/db-refresh-scripts.md.
-- Reflects local dev's current schema (production plus whatever's pending in
-- unapplied_updates.sql), not production's schema directly.

-- MySQL dump 10.13  Distrib 8.1.0, for Win64 (x86_64)
--
-- Host: localhost    Database: mismo
-- ------------------------------------------------------
-- Server version	8.1.0

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `app_setting`
--

DROP TABLE IF EXISTS `app_setting`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `app_setting` (
  `setting_key` varchar(100) NOT NULL,
  `setting_value` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `configuration`
--

DROP TABLE IF EXISTS `configuration`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `configuration` (
  `configuration_id` int NOT NULL AUTO_INCREMENT,
  `world_name` varchar(250) NOT NULL,
  `island_name` varchar(250) NOT NULL,
  `generation` int NOT NULL,
  `generation_score` double NOT NULL,
  `generated_date` datetime NOT NULL,
  `hash_for_signature` varchar(250) NOT NULL,
  `configuration_script` text NOT NULL,
  `organization_id` int NOT NULL,
  `created_by_user_id` int DEFAULT NULL,
  `island_credential_id` int DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `is_template` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`configuration_id`),
  KEY `idx_configuration_organization_id` (`organization_id`),
  KEY `idx_configuration_organization_world` (`organization_id`,`world_name`),
  KEY `idx_configuration_organization_world_island` (`organization_id`,`world_name`,`island_name`),
  KEY `idx_configuration_island_credential_id` (`island_credential_id`),
  KEY `fk_configuration_created_by_user` (`created_by_user_id`),
  CONSTRAINT `fk_configuration_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `user` (`user_id`),
  CONSTRAINT `fk_configuration_island_credential` FOREIGN KEY (`island_credential_id`) REFERENCES `island_credential` (`island_credential_id`),
  CONSTRAINT `fk_configuration_organization` FOREIGN KEY (`organization_id`) REFERENCES `organization` (`organization_id`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `evaluation`
--

DROP TABLE IF EXISTS `evaluation`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `evaluation` (
  `evaluation_id` int NOT NULL AUTO_INCREMENT,
  `organization_id` int NOT NULL,
  `match_set_id` int NOT NULL,
  `configuration_id` int NOT NULL,
  `run_by_user_id` int DEFAULT NULL,
  `run_at` datetime NOT NULL,
  `total_cases` int NOT NULL,
  `scorable_cases` int NOT NULL,
  `not_sure_cases` int NOT NULL,
  `agree_count` int NOT NULL,
  `disagree_count` int NOT NULL,
  `score` double DEFAULT NULL,
  PRIMARY KEY (`evaluation_id`),
  KEY `idx_evaluation_organization_id` (`organization_id`),
  KEY `idx_evaluation_match_set_id` (`match_set_id`),
  KEY `idx_evaluation_configuration_id` (`configuration_id`),
  KEY `idx_evaluation_match_set_configuration` (`match_set_id`,`configuration_id`,`run_at`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `evaluation_result`
--

DROP TABLE IF EXISTS `evaluation_result`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `evaluation_result` (
  `evaluation_result_id` int NOT NULL AUTO_INCREMENT,
  `evaluation_id` int NOT NULL,
  `match_item_id` int NOT NULL,
  `expected_classification` varchar(20) NOT NULL,
  `calculated_classification` varchar(20) NOT NULL,
  `signature` varchar(500) DEFAULT NULL,
  `agrees` tinyint(1) NOT NULL,
  PRIMARY KEY (`evaluation_result_id`),
  KEY `idx_evaluation_result_evaluation_id` (`evaluation_id`),
  KEY `idx_evaluation_result_evaluation_agrees` (`evaluation_id`,`agrees`),
  KEY `idx_evaluation_result_evaluation_signature` (`evaluation_id`,`signature`),
  KEY `idx_evaluation_result_match_item_id` (`match_item_id`)
) ENGINE=InnoDB AUTO_INCREMENT=13593 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `island_credential`
--

DROP TABLE IF EXISTS `island_credential`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `island_credential` (
  `island_credential_id` int NOT NULL AUTO_INCREMENT,
  `organization_id` int NOT NULL,
  `name` varchar(250) NOT NULL,
  `credential_hash` varchar(250) NOT NULL,
  `created_by_user_id` int DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `last_used_at` datetime DEFAULT NULL,
  `revoked_at` datetime DEFAULT NULL,
  PRIMARY KEY (`island_credential_id`),
  UNIQUE KEY `uq_island_credential_hash` (`credential_hash`),
  KEY `idx_island_credential_organization_id` (`organization_id`),
  KEY `fk_island_credential_created_by_user` (`created_by_user_id`),
  CONSTRAINT `fk_island_credential_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `user` (`user_id`),
  CONSTRAINT `fk_island_credential_organization` FOREIGN KEY (`organization_id`) REFERENCES `organization` (`organization_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `match_item`
--

DROP TABLE IF EXISTS `match_item`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `match_item` (
  `match_item_id` int NOT NULL AUTO_INCREMENT,
  `match_set_id` int NOT NULL,
  `label` varchar(250) NOT NULL,
  `description` varchar(1000) DEFAULT NULL,
  `patient_data_a` text NOT NULL,
  `patient_data_b` text NOT NULL,
  `expect_status` varchar(20) NOT NULL,
  `data_source` varchar(120) NOT NULL,
  `created_by_user_id` int DEFAULT NULL,
  `updated_by_user_id` int DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `original_expect_status` varchar(20) DEFAULT NULL,
  `is_reviewed` tinyint(1) NOT NULL DEFAULT '0',
  `needs_review` tinyint(1) NOT NULL DEFAULT '0',
  `provenance_type` varchar(30) NOT NULL DEFAULT 'MANUAL',
  `copied_from_match_item_id` int DEFAULT NULL,
  `source_signature` varchar(500) DEFAULT NULL,
  `review_notes` text,
  PRIMARY KEY (`match_item_id`),
  KEY `idx_match_item_match_set_id` (`match_set_id`),
  KEY `idx_match_item_match_set_label` (`match_set_id`,`label`),
  KEY `fk_match_item_created_by_user` (`created_by_user_id`),
  KEY `fk_match_item_updated_by_user` (`updated_by_user_id`),
  KEY `idx_match_item_copied_from_match_item_id` (`copied_from_match_item_id`),
  CONSTRAINT `fk_match_item_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `user` (`user_id`),
  CONSTRAINT `fk_match_item_match_set` FOREIGN KEY (`match_set_id`) REFERENCES `match_set` (`match_set_id`),
  CONSTRAINT `fk_match_item_updated_by_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `user` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=32621 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `match_item_review`
--

DROP TABLE IF EXISTS `match_item_review`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `match_item_review` (
  `match_item_review_id` int NOT NULL AUTO_INCREMENT,
  `match_item_id` int NOT NULL,
  `reviewer_user_id` int NOT NULL,
  `classification` varchar(20) NOT NULL,
  `notes` text,
  `reviewed_at` datetime NOT NULL,
  PRIMARY KEY (`match_item_review_id`),
  KEY `idx_match_item_review_match_item_id` (`match_item_id`,`reviewed_at`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `match_set`
--

DROP TABLE IF EXISTS `match_set`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `match_set` (
  `match_set_id` int NOT NULL AUTO_INCREMENT,
  `label` varchar(250) NOT NULL,
  `organization_id` int NOT NULL,
  `created_by_user_id` int DEFAULT NULL,
  `updated_by_user_id` int DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `is_template` tinyint(1) NOT NULL DEFAULT '0',
  `lifecycle_status` varchar(20) NOT NULL DEFAULT 'DRAFT',
  `version` varchar(50) DEFAULT NULL,
  `copied_from_match_set_id` int DEFAULT NULL,
  `root_match_set_id` int NOT NULL DEFAULT '0',
  `archived_at` datetime DEFAULT NULL,
  PRIMARY KEY (`match_set_id`),
  KEY `idx_match_set_organization_id` (`organization_id`),
  KEY `idx_match_set_organization_label` (`organization_id`,`label`),
  KEY `fk_match_set_created_by_user` (`created_by_user_id`),
  KEY `fk_match_set_updated_by_user` (`updated_by_user_id`),
  KEY `idx_match_set_root_match_set_id` (`root_match_set_id`),
  KEY `idx_match_set_copied_from_match_set_id` (`copied_from_match_set_id`),
  CONSTRAINT `fk_match_set_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `user` (`user_id`),
  CONSTRAINT `fk_match_set_organization` FOREIGN KEY (`organization_id`) REFERENCES `organization` (`organization_id`),
  CONSTRAINT `fk_match_set_updated_by_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `user` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `organization`
--

DROP TABLE IF EXISTS `organization`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `organization` (
  `organization_id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(250) NOT NULL,
  `domain` varchar(250) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `is_template_org` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`organization_id`),
  UNIQUE KEY `uq_organization_domain` (`domain`),
  KEY `idx_organization_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `signature_batch`
--

DROP TABLE IF EXISTS `signature_batch`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `signature_batch` (
  `signature_batch_id` int NOT NULL AUTO_INCREMENT,
  `organization_id` int NOT NULL,
  `label` varchar(250) DEFAULT NULL,
  `uploaded_by_user_id` int DEFAULT NULL,
  `uploaded_at` datetime NOT NULL,
  PRIMARY KEY (`signature_batch_id`),
  KEY `idx_signature_batch_organization_id` (`organization_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `signature_batch_entry`
--

DROP TABLE IF EXISTS `signature_batch_entry`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `signature_batch_entry` (
  `signature_batch_entry_id` int NOT NULL AUTO_INCREMENT,
  `signature_batch_id` int NOT NULL,
  `signature` varchar(500) NOT NULL,
  `count` int NOT NULL,
  PRIMARY KEY (`signature_batch_entry_id`),
  KEY `idx_signature_batch_entry_signature_batch_id` (`signature_batch_id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `user`
--

DROP TABLE IF EXISTS `user`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `user` (
  `user_id` int NOT NULL AUTO_INCREMENT,
  `email` varchar(120) DEFAULT NULL,
  `hub_user_id` varchar(64) DEFAULT NULL,
  `organization_id` int NOT NULL,
  `display_name` varchar(250) DEFAULT NULL,
  `first_name` varchar(120) DEFAULT NULL,
  `last_name` varchar(120) DEFAULT NULL,
  `title` varchar(250) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `last_login_at` datetime DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `uq_user_hub_user_id` (`hub_user_id`),
  KEY `idx_user_organization_id` (`organization_id`),
  CONSTRAINT `fk_user_organization` FOREIGN KEY (`organization_id`) REFERENCES `organization` (`organization_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping events for database 'mismo'
--

--
-- Dumping routines for database 'mismo'
--
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2026-08-19  8:01:45
