-- unapplied_updates.sql
--
-- Pending, not-yet-released database changes. Applied manually against a
-- local copy of the database before development/testing (see
-- docs/v2-roadmap.md §8), then folded into a dated/versioned snapshot
-- (e.g. upgrade-2.1.sql) and reset to empty on release.
--
-- This is NOT applied automatically as part of the build, and has not been
-- run against any live database.
--
-- Empty as of the v2.0 release -- everything that had accumulated here was
-- copied into upgrade-2.0.sql and this file was reset. See that file for
-- the full v2.0 change history.
